[package]
name = "foyer-intrusive"
version = "0.1.0"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "Hybrid cache for Rust"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bytes = "1"
cmsketch = "0.1"
foyer-common = { path = "../foyer-common" }
itertools = "0.10.5"
memoffset = "0.8"
parking_lot = "0.12"
paste = "1.0"
thiserror = "1"
tracing = "0.1"
twox-hash = "1"
