[package]
name = "foyer-storage"
version = "0.1.0"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "Hybrid cache for Rust"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-udeps.ignore]
normal = ["foyer-workspace-hack"]

[dependencies]
anyhow = "1.0"
async-channel = "1.8"
bitflags = "2.3.1"
bitmaps = "3.2"
bytes = "1"
cmsketch = "0.1"
foyer-common = { path = "../foyer-common" }
foyer-intrusive = { path = "../foyer-intrusive" }
foyer-workspace-hack = { version = "0.1", path = "../foyer-workspace-hack" }
futures = "0.3"
itertools = "0.11.0"
libc = "0.2"
memoffset = "0.9"
nix = { version = "0.27", features = ["fs", "mman", "uio"] }
parking_lot = { version = "0.12", features = ["arc_lock"] }
paste = "1.0"
prometheus = "0.13"
rand = "0.8.5"
thiserror = "1"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tracing = "0.1"
twox-hash = "1"

[dev-dependencies]
bytesize = "1"
clap = { version = "4", features = ["derive"] }
hdrhistogram = "7"
rand_mt = "4.2.1"
tempfile = "3"

[features]
deadlock = ["parking_lot/deadlock_detection"]
