[package]
name = "foyer-storage"
version = "0.7.6"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "storage engine for foyer - the hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
# TODO(MrCroxx): Remove this after `allocator_api` is stable.
allocator-api2 = { version = "0.2", default-features = false }
anyhow = "1.0"
# TODO(MrCroxx): use `array_chunks` after `#![feature(array_chunks)]` is stable.
array-util = "1"
async-channel = "2"
bincode = "1"
bitflags = "2.3.1"
bytes = "1"
either = "1"
foyer-common = { version = "0.6", path = "../foyer-common" }
foyer-memory = { version = "0.3", path = "../foyer-memory" }
futures = "0.3"
itertools = "0.12"
lazy_static = "1"
lz4 = "1.24"
memoffset = "0.9"
parking_lot = { version = "0.12", features = ["arc_lock"] }
pin-project = "1"
rand = "0.8"
serde = { workspace = true }
thiserror = "1"
tokio = { workspace = true }
tracing = "0.1"
twox-hash = "1"
zstd = "0.13"

[dev-dependencies]
tempfile = "3"
test-log = { workspace = true }

[features]
default = []
deadlock = ["parking_lot/deadlock_detection"]
nightly = ["allocator-api2/nightly"]
