[workspace]
resolver = "2"
members = [
    "examples",
    "foyer",
    "foyer-common",
    "foyer-experimental",
    "foyer-experimental-bench",
    "foyer-intrusive",
    "foyer-memory",
    "foyer-storage",
    "foyer-storage-bench",
]

[workspace.dependencies]
tokio = { package = "madsim-tokio", version = "0.2", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
serde = { version = "1", features = ["derive", "rc"] }

[profile.release]
debug = true
