[workspace]

members = [
    "foyer",
    "foyer-bench",
    "foyer-common",
    "foyer-intrusive",
    "foyer-policy",
    "foyer-storage",
    "foyer-storage-bench",
    "foyer-utils",
]

[patch.crates-io]
# cmsketch = { path = "../cmsketch-rs" }
