[workspace]

members = [
    "foyer",
    "foyer-common",
    "foyer-intrusive",
    "foyer-memory",
    "foyer-storage",
    "foyer-storage-bench",
    "foyer-workspace-hack",
]

[patch.crates-io]
# cmsketch = { path = "../cmsketch-rs" }

[profile.release]
debug = 1
