[package]
name = "foyer-memory"
version = "0.7.1"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "memory cache for foyer - the hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/foyer-rs/foyer"
homepage = "https://github.com/foyer-rs/foyer"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
bitflags = "2"
cmsketch = "0.2.1"
fastrace = { workspace = true }
foyer-common = { version = "0.9.1", path = "../foyer-common" }
foyer-intrusive = { version = "0.9.1", path = "../foyer-intrusive" }
futures = "0.3"
hashbrown = "0.14"
itertools = { workspace = true }
parking_lot = "0.12"
pin-project = "1"
serde = { workspace = true }
tokio = { workspace = true }
tracing = "0.1"

[dev-dependencies]
anyhow = "1"
csv = "1.3.0"
moka = { version = "0.12", features = ["sync"] }
rand = { version = "0.8", features = ["small_rng"] }
test-log = { workspace = true }
zipf = "7.0.1"

[features]
deadlock = ["parking_lot/deadlock_detection"]
strict_assertions = [
    "foyer-common/strict_assertions",
    "foyer-intrusive/strict_assertions",
]
sanity = ["strict_assertions"]
mtrace = ["fastrace/enable", "foyer-common/mtrace"]

[[bench]]
name = "bench_hit_ratio"
harness = false

[[bench]]
name = "bench_dynamic_dispatch"
harness = false
