[package]
name = "foyer-memory"
version = "0.3.6"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "memory cache for foyer - the hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
bitflags = "2"
cmsketch = "0.2"
foyer-common = { version = "0.6", path = "../foyer-common" }
foyer-intrusive = { version = "0.5", path = "../foyer-intrusive" }
futures = "0.3"
hashbrown = "0.14"
itertools = "0.12"
libc = "0.2"
parking_lot = "0.12"
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
csv = "1.3.0"
moka = { version = "0", features = ["sync"] }
rand = { version = "0.8", features = ["small_rng"] }
zipf = "7.0.1"

[features]
deadlock = ["parking_lot/deadlock_detection"]

[[bench]]
name = "bench_hit_ratio"
harness = false

[[bench]]
name = "bench_dynamic_dispatch"
harness = false
