[package]
name = "foyer-memory"
version = "0.1.0"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "Hybrid cache for Rust"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-udeps.ignore]
normal = ["foyer-workspace-hack"]

[dependencies]
bytes = "1"
cmsketch = "0.1"
foyer-common = { path = "../foyer-common" }
foyer-intrusive = { path = "../foyer-intrusive" }
foyer-workspace-hack = { version = "0.1", path = "../foyer-workspace-hack" }
libc = "0.2"
memoffset = "0.9"
parking_lot = "0.12"
paste = "1.0"
rand = "0.8.5"
tracing = "0.1"
twox-hash = "1"

[dev-dependencies]
bytesize = "1"
clap = { version = "4", features = ["derive"] }
hdrhistogram = "7"
rand_mt = "4.2.1"
tempfile = "3"

[features]
deadlock = ["parking_lot/deadlock_detection"]
