[package]
name = "foyer-bench"
version = "0.1.0"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "bench tool for foyer - the hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bytesize = "1"
clap = { version = "4", features = ["derive"] }
console-subscriber = { version = "0.2", optional = true }
foyer = { version = "0.8", path = "../foyer" }
futures = "0.3"
hdrhistogram = "7"
http-body-util = "0.1"
hyper = { version = "1.0", features = ["server", "http1", "http2"] }
hyper-util = { version = "0.1", features = [
    "server",
    "server-auto",
    "http1",
    "http2",
    "tokio",
] }
indexmap = "2"
itertools = "0.12"
libc = "0.2"
metrics = "0.22"
metrics-exporter-prometheus = "0.14"
metrics-util = { version = "0.16" }
nix = { version = "0.28", features = ["fs", "mman"] }
opentelemetry = { version = "0.22", optional = true }
opentelemetry-otlp = { version = "0.15.0", optional = true }
opentelemetry-semantic-conventions = { version = "0.14", optional = true }
opentelemetry_sdk = { version = "0.22", features = [
    "rt-tokio",
    "trace",
], optional = true }
parking_lot = "0.12"
rand = "0.8.5"
serde = { workspace = true }
serde_bytes = "0.11.14"
tokio = { workspace = true }
tracing = "0.1"
tracing-opentelemetry = { version = "0.23", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zipf = "7"

[features]
deadlock = ["parking_lot/deadlock_detection", "foyer/deadlock"]
tokio-console = ["console-subscriber"]
trace = [
    "opentelemetry",
    "opentelemetry_sdk",
    "opentelemetry-otlp",
    "tracing-opentelemetry",
    "opentelemetry-semantic-conventions",
]
