[package]
name = "foyer-bench"
version = "0.2.1"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "bench tool for foyer - the hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bytesize = "1"
clap = { version = "4", features = ["derive"] }
console-subscriber = { version = "0.2", optional = true }
foyer = { version = "0.10.1", path = "../foyer" }
futures = "0.3"
hdrhistogram = "7"
itertools = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = "0.15"
minitrace = { workspace = true, optional = true }
minitrace-jaeger = { workspace = true, optional = true }
opentelemetry = { version = "0.23", optional = true }
opentelemetry-otlp = { version = "0.16", optional = true }
opentelemetry-semantic-conventions = { version = "0.15", optional = true }
opentelemetry_sdk = { version = "0.23", features = [
    "rt-tokio",
    "trace",
], optional = true }
parking_lot = "0.12"
rand = "0.8.5"
serde = { workspace = true }
serde_bytes = "0.11.14"
tokio = { workspace = true }
tracing = "0.1"
tracing-opentelemetry = { version = "0.24", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zipf = "7"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5", optional = true }

[features]
deadlock = ["parking_lot/deadlock_detection", "foyer/deadlock"]
tokio-console = ["console-subscriber"]
trace = [
    "opentelemetry",
    "opentelemetry_sdk",
    "opentelemetry-otlp",
    "tracing-opentelemetry",
    "opentelemetry-semantic-conventions",
]
strict_assertions = ["foyer/strict_assertions"]
sanity = ["foyer/sanity"]
jemalloc = ["tikv-jemallocator"]
mtrace = ["foyer/mtrace", "minitrace-jaeger", "minitrace"]
