[package]
name = "foyer-bench"
version = "0.3.3"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "bench tool for foyer - the hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/foyer-rs/foyer"
homepage = "https://github.com/foyer-rs/foyer"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bytesize = { workspace = true }
clap = { workspace = true }
console-subscriber = { version = "0.4", optional = true }
fastrace = { workspace = true, optional = true }
fastrace-jaeger = { workspace = true, optional = true }
foyer = { version = "0.11.3", path = "../foyer" }
futures = "0.3"
hdrhistogram = "7"
itertools = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = "0.15"
parking_lot = "0.12"
rand = "0.8.5"
serde = { workspace = true }
serde_bytes = "0.11.15"
tokio = { workspace = true }
tracing = "0.1"
tracing-opentelemetry = { version = "0.26", optional = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zipf = "7"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6", optional = true }

[features]
deadlock = ["parking_lot/deadlock_detection", "foyer/deadlock"]
tokio-console = ["console-subscriber"]
strict_assertions = ["foyer/strict_assertions"]
sanity = ["foyer/sanity"]
jemalloc = ["tikv-jemallocator"]
mtrace = ["foyer/mtrace", "fastrace-jaeger", "fastrace"]
