[package]
name = "foyer"
version = "0.8.8"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "Hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
readme = "../README.md"
rust-version = "1.76"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
anyhow = "1"
foyer-common = { version = "0.6", path = "../foyer-common" }
foyer-intrusive = { version = "0.5", path = "../foyer-intrusive" }
foyer-memory = { version = "0.3", path = "../foyer-memory" }
foyer-storage = { version = "0.7", path = "../foyer-storage" }

[features]
default = []
nightly = ["foyer-storage/nightly"]
