[package]
name = "foyer"
version = "0.9.4"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "Hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
readme = "../README.md"
rust-version = "1.77"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
anyhow = "1"
foyer-common = { version = "0.7.3", path = "../foyer-common" }
foyer-memory = { version = "0.5.2", path = "../foyer-memory" }
foyer-storage = { version = "0.8.5", path = "../foyer-storage" }
minitrace = { workspace = true }
tokio = { workspace = true }
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
test-log = { workspace = true }

[features]
default = []
nightly = ["foyer-storage/nightly"]
deadlock = ["foyer-storage/deadlock"]
strict_assertions = [
    "foyer-common/strict_assertions",
    "foyer-memory/strict_assertions",
    "foyer-storage/strict_assertions",
]
sanity = ["strict_assertions", "foyer-memory/sanity"]
mtrace = ["minitrace/enable", "foyer-memory/mtrace", "foyer-storage/mtrace"]
