[package]
name = "foyer"
version = "0.1.0"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "Hybrid cache for Rust"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-udeps.ignore]
normal = ["foyer-workspace-hack"]

[dependencies]
foyer-common = { path = "../foyer-common" }
foyer-intrusive = { path = "../foyer-intrusive" }
foyer-storage = { path = "../foyer-storage" }
foyer-workspace-hack = { version = "0.1", path = "../foyer-workspace-hack" }
