[package]
name = "foyer"
version = "0.4.0"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "Hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-udeps.ignore]
normal = ["foyer-workspace-hack"]

[dependencies]
foyer-common = { version = "0.2", path = "../foyer-common" }
foyer-intrusive = { version = "0.1", path = "../foyer-intrusive" }
foyer-storage = { version = "0.3", path = "../foyer-storage" }
foyer-workspace-hack = { version = "0.1", path = "../foyer-workspace-hack" }
