[package]
name = "foyer"
version = "0.11.5"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "Hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/foyer-rs/foyer"
homepage = "https://github.com/foyer-rs/foyer"
readme = "../README.md"
rust-version = "1.81.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
anyhow = "1"
fastrace = { workspace = true }
foyer-common = { version = "0.9.5", path = "../foyer-common" }
foyer-memory = { version = "0.7.5", path = "../foyer-memory" }
foyer-storage = { version = "0.10.5", path = "../foyer-storage" }
futures = "0.3"
pin-project = "1"
tokio = { workspace = true }
tracing = "0.1"

[dev-dependencies]
tempfile = "3"
test-log = { workspace = true }

[features]
default = []
nightly = ["foyer-storage/nightly"]
deadlock = ["foyer-storage/deadlock"]
strict_assertions = [
    "foyer-common/strict_assertions",
    "foyer-memory/strict_assertions",
    "foyer-storage/strict_assertions",
]
sanity = ["strict_assertions", "foyer-memory/sanity"]
mtrace = [
    "fastrace/enable",
    "foyer-common/mtrace",
    "foyer-memory/mtrace",
    "foyer-storage/mtrace",
]
