[package]
name = "examples"
version = "0.0.0"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "Hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
publish = false

[dependencies]
ahash = "0.8"
anyhow = "1"
chrono = "0.4"
fastrace = { workspace = true }
fastrace-jaeger = { workspace = true, optional = true }
fastrace-opentelemetry = { workspace = true, optional = true }
foyer = { version = "*", path = "../foyer" }
opentelemetry = { version = "0.23", optional = true }
opentelemetry-otlp = { version = "0.16", optional = true }
opentelemetry-semantic-conventions = { version = "0.15", optional = true }
opentelemetry_sdk = { version = "0.23", features = [
    "rt-tokio",
    "trace",
], optional = true }
tempfile = "3"
tokio = { version = "1", features = ["rt"] }

[features]
jaeger = ["fastrace-jaeger"]
ot = [
    "fastrace-opentelemetry",
    "opentelemetry",
    "opentelemetry-otlp",
    "opentelemetry-semantic-conventions",
    "opentelemetry_sdk",
]

[[example]]
name = "memory"
path = "memory.rs"

[[example]]
name = "hybrid"
path = "hybrid.rs"

[[example]]
name = "hybrid_full"
path = "hybrid_full.rs"

[[example]]
name = "event_listener"
path = "event_listener.rs"

[[example]]
name = "tail_based_tracing"
path = "tail_based_tracing.rs"
