[package]
name = "examples"
version = "0.0.0"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "Hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
publish = false

[dependencies]
ahash = "0.8"
anyhow = "1"
chrono = "0.4"
foyer = { version = "*", path = "../foyer" }
tempfile = "3"
tokio = { version = "1", features = ["rt"] }

[[example]]
name = "memory"
path = "memory.rs"

[[example]]
name = "hybrid"
path = "hybrid.rs"

[[example]]
name = "hybrid_full"
path = "hybrid_full.rs"

[[example]]
name = "event_listener"
path = "event_listener.rs"
