[package]
name = "foyer-common"
version = "0.6.4"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "common utils for foyer - the hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
cfg-if = "1"
crossbeam = "0.8"
hashbrown = "0.14"
itertools = "0.12"
nix = { version = "0.28", features = ["fs"] }
parking_lot = { version = "0.12", features = ["arc_lock"] }
rustversion = "1.0"
serde = { workspace = true }
tokio = { workspace = true }
libc = "0.2"

[dev-dependencies]
futures = "0.3"
rand = "0.8.5"
