[package]
name = "foyer-common"
version = "0.6.2"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "common utils for foyer - the hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.cargo-udeps.ignore]
normal = ["foyer-workspace-hack"]

[dependencies]
ahash = "0.8"
anyhow = "1.0"
bytes = "1"
cfg-if = "1"
crossbeam = "0.8"
foyer-workspace-hack = { version = "0.5", path = "../foyer-workspace-hack" }
hashbrown = "0.14"
itertools = "0.12"
nix = { version = "0.28", features = ["fs"] }
parking_lot = { version = "0.12", features = ["arc_lock"] }
paste = "1.0"
serde = "1"
tokio = { workspace = true }
tracing = "0.1"

[dev-dependencies]
rand = "0.8.5"
