[package]
name = "foyer-common"
version = "0.8.1"
edition = "2021"
authors = ["MrCroxx <mrcroxx@outlook.com>"]
description = "common components for foyer - the hybrid cache for Rust"
license = "Apache-2.0"
repository = "https://github.com/mrcroxx/foyer"
homepage = "https://github.com/mrcroxx/foyer"
readme = "../README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1"
bytes = "1"
cfg-if = "1"
crossbeam = "0.8"
futures = "0.3"
hashbrown = "0.14"
itertools = { workspace = true }
metrics = { workspace = true }
fastrace = { workspace = true }
nix = { version = "0.29", features = ["fs"] }
parking_lot = { version = "0.12", features = ["arc_lock"] }
pin-project = "1"
rustversion = "1.0"
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
futures = "0.3"
rand = "0.8.5"

[features]
strict_assertions = []
mtrace = ["fastrace/enable"]
