name: License Check

on:
  push:
    branches:
    - main
    - "forks/*"
  pull_request:
    branches: 
    - main
    - "release-*.*"
    
jobs:
  license-header-check:
    runs-on: ubuntu-latest
    name: license-header-check
    steps:
    - uses: actions/checkout@v3
    - name: Check License Header
      uses: apache/skywalking-eyes/header@v0.6.0
