name: "Misc Check"

on:
  push:
    branches:
      - "main"
      - "forks/*"
  pull_request:
    branches:
      - "main"
      - "release-*.*"

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  misc-check:
    name: misc check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run typos check
        uses: crate-ci/typos@master
      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${BINARY}.tar.gz -O - | tar xz && sudo mv ${BINARY} /usr/bin/yq
        env:
          YQ_VERSION: v4.16.1
          BINARY: yq_linux_amd64
          BUF_VERSION: 1.0.0-rc6
      - name: Install jq
        uses: dcarbone/install-jq-action@v2.0.2
      - name: Check if Grafana dashboards are minimized
        run: |
          ./scripts/minimize-dashboards.sh --check
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master